import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LocationProvider } from "@/components/LocationContext";

const serperKey = process.env.SERPER_API_KEY;
if (!serperKey) console.warn("BRAK KLUCZA: SERPER_API_KEY w .env.local");
if (serperKey) console.log("ENV CHECK: Silnik wyszukiwania (Serper) skonfigurowany.");

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LocationProvider>
          {children}
        </LocationProvider>
      </body>
    </html>
  );
}
